name: Run R Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R Packages
        run: |
          Rscript -e 'install.packages(c("tidyverse", "lubridate"))'

      - name: Run R Script
        run: |
          mkdir -p output
          Rscript analysis.R

      - name: Upload Output Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ride-analysis-output
          path: output/avg_ride_length.csv
